---
- name: 사용자 정의 팩트를 사용한 웹 서버 설정
  hosts: webserver
  gather_facts: true
  tasks:
  ################################################
  # 1) 패키지 설치
  # 2) 서비스 기동
  # 3) 서비스 설정 <- 이건 스킵
  # 4) 방화벽 등록
  ###############################################
  - name: 1) 방화벽 해제 - {{ ansible_local.custom.general.fwsvc }} 
    ansible.posix.firewalld:
      service: "{{ ansible_local.custom.general.fwsvc }}"
      permanent: true
      immediate: true
      state: disabled

  - name: 2) 서비스 정지 - {{ ansible_local.custom.general.service }}
    ansible.builtin.service:
      name: "{{ ansible_local.custom.general.service }}"
      state: stopped
      enabled: false
  
  - name: 3) 파일 제거 
    ansible.builtin.file:
      path: /etc/ansible/facts.d
      state: absent


  
