---
- name: 0) 작업 제어 실습
  hosts: webservers
  gather_facts: true
  vars_files:
    - vars/vars.yml
  tasks:
    ##############################################
    # 0) 점검 - MEM > 256, 배포판: CentOS9
    # 1) 패키지 설치 - httpd, mod_ssl, firewalld
    # 2) 서비스 기동 - httpd, firewalld
    # 3) 웹 서버 설정(notify)
    #   * /etc/pki/tls/certs/localhost.crt
    #   * /etc/pki/tls/private/localhost.key
    #   * /var/www/html/index.html
    # 4) 방화벽 포트 등록 - http, https
    # 5) handlers 정의
    ##############################################
    - name: 0) 점검 - MEM > 256, 배포판- CentOS
      ansible.builtin.fail:
        msg: "[ FAIL ] 메모리가 256MB보다 작거나 CentOS 배포판이 아닙니다."
      when: >
        ansible_distribution != "CentOS" or
        ansible_memtotal_mb < min_ram_mb
    - name: 0) 점검 - CentOS 9버전 확인
      ansible.builtin.debug:
        msg: "CentOS Stream 9버전에서만 동작합니다."
      failed_when: ansible_distribution_version != "9"

    - name: 1) 패키지 설치 - {{ packages }}
      ansible.builtin.dnf:
        name: "{{ packages }}"
        state: present
    
    - name: 2) 서비스 기동 - {{ services }}
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
        enabled: yes 
      loop: "{{ services }}"
    
    - name: Block ~ Rescue
      block:
      - name: 3) 웹 서버 설정(notify)
        ansible.builtin.copy:
          src: "{{ item.src }}"
          dest: "{{ item.dest }}"
          owner: "{{ item.owner }}"
          group: "{{ item.group }}"
          mode: "{{ item.mode }}"
        loop: "{{ web_config_files }}"
        notify: restart_web_server
      rescue:
        - name: 3) 웹 서버 설정 오류 발생
          ansible.builtin.debug:
            msg: "[ FAIL ] 웹 서버 설정 중 오류가 발생했습니다."
    
    - name: 4) 방화벽 포트 등록 - http, https
      ansible.posix.firewalld:
        service: "{{ item }}"
        permanent: true
        immediate: true
        state: enabled
      loop: "{{ firewall_rules }}"
  handlers:
    - name: restart_web_server
      ansible.builtin.systemd:
        name: "{{ services }}"
        state: restarted



