---
- name: Restore_site.yml
  hosts: all
  tasks:
  #####################################################
  # 1) 방화벽 포트 제거 - http
  # 2) 서비스 종료      - httpd, firewalld
  # 3) 서비스 설정 삭제 - /var/www/html/index.html 제거
  # 4) 패키지 삭제      - httpd
  #####################################################
  - name: 방화벽 포트 제거 - (firewalld) httpd
    ansible.posix.firewalld:
      service: http
      permanent: true
      immediate: true
      state: disabled

  - name: 2-1) 서비스 종료      - httpd
    ansible.builtin.service:
      name: httpd
      state: stopped
      enabled: false
  - name: 2-2) 서비스 종료      - firewalld
    ansible.builtin.service:
      name: firewalld
      state: stopped
      enabled: false
  - name: 3) 서비스 설정 삭제 - (file에서 확인)/var/www/html/index.html 제거
    ansible.builtin.file:
      path: /var/www/html/index.html
      state: absent
  - name: 4) 패키지 삭제
    ansible.builtin.yum:
      name: httpd
      state: absent
