---
- name: 3-Tier Architecture 제거
  hosts: all
  tasks:
    - name: 1) 방화벽 제거 
      ansible.posix.firewalld:
            service: "{{ item }}"
            permanent: true
            immediate: true
            state: disabled
      loop:
        - mysql
        - http
        - https

    - name: 2) 서비스 종료 - httpd, mariadb
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
        enabled: false
      loop:
        - httpd
        - mariadb
    - name: 3) 설정 삭제 - /var/www/html/index.php, /var/lib/mysql
      ansible.builtin.file:
        path: /var/www/html/index.php
        state: absent
      loop:
        - /var/www/html/index.php
        - /var/lib/mysql
    - name: 4) DB 패키지 삭제
      ansible.builtin.dnf:
            name:
              - httpd
              - mod_ssl
              - mariadb
              - mariadb-server
              - python3-PyMySQL
            state: absent
