---
- name: Restore playbook.yml
  hosts: all
  vars:
    web_package: httpd
    db_package: mariadb-server
    db_service: mariadb
  tasks:
    - name: Check local time
      ansible.builtin.command: date
      register: command_result
      changed_when: false

    - name: Print local time
      ansible.builtin.debug:
        var: command_result.stdout
    - name: Attepmt to set up a web server
      block:
        - name: 서비스 중지
          ansible.builtin.service:
            name: "{{ db_service }}"
            state: stopped
            enabled: false

        - name: 패키지 삭제
          ansible.builtin.yum:
            name: 
              - "{{ web_package }}"
              - "{{ db_package }}"
            state: absent
      rescue:
        - name: 패키지 삭제 에러 메세지
          ansible.builtin.debug:
            msg: "[ FAIL ] 패키지 삭제가 되지 않았습니다. - {{ web_package }} {{ db_package }}"
