---
##########################################################
# 작업
# * 사용자/암호 추가: developer/developer
# * 키 쌍 배포(pubkey 배포)
# * /etc/sudoers.d/developer
#   ----------------------------------
#   developer ALL: (ALL) NOPASSWD: ALL
#   ----------------------------------
##########################################################
- name: 1) 사용자 추가 - developer
  hosts: all
  gather_facts: false
  vars:
    username: developer
    pw: developer 
  tasks:
    - name: 사용자/암호 추가 - developer/developer
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ pw | password_hash('sha512') }}"

    - name: 키 쌍 배포(pubkey 배포)
      ansible.posix.authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"
    
    - name: /etc/sudoers.d/developer 파일 생성
      ansible.builtin.copy:
        content: "{{ username }} ALL=(ALL) NOPASSWD: ALL\n"
        dest: "/etc/sudoers.d/{{ username }}"